# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20bfef7b730d11552b86fd6f58e66ccad548d3dd12827ff0321dee3d7ce058a518c932a6d91fa3ed8a819f57952637999b8482051d8dadd78fc642e304af7bc6

test:
  secret_key_base: 9178f2b0b749dad3ec7ab8fa782caf7fa2cc2efb35f61d55f9f5ffba66a1ba416ff6933a54867b48931e2e1302f7d932202f9c504b1126db4de3685bee484a5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
